### ISSUE TITLE
ESP8266 SPIFF

### ISSUE THREAD

**Issue by JefersonDeLeon** [thebigpotatoe/Effortless-SPIFFS#14]
What is the reason of using LittleFS instead of SPIFF for ESP8266?
I have encounter problem in parsing Json using SPIFF with large data. and while searching for solution i found your library.
do you have explanation why to use LittleFS?
```
#if defined(ESP8266)
#include <LittleFS.h>
```

**Comment by thebigpotatoe** [comment]
[SPIFFS is now depreciated](https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#spiffs-deprecation-warning)
