### ISSUE TITLE
Migrate to LittleFS

### ISSUE THREAD

**Issue by rgm3** [thebigpotatoe/Effortless-SPIFFS#3]
The SPIFFS filesystem is deprecated and not being supported by upstream anymore:
https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#spiffs-deprecation-warning

Aside from the relatively simple task of search/replacing `SPIFFS.` with `LittleFS.` you might consider updating the library's name or some function names.  Perhaps "eLittleFS" for the class or "EespFS."

**Comment by thebigpotatoe** [comment]
So I saw. Thanks for the suggestions, I'll have to make an update soon

**Comment by CelsoCaldeira** [comment]
Does the saveFile/saveToFile methods overwrite or append the previous content of the file?
Do I need to create the files and upload via arduinoIDE( example) before using it?

**Comment by thebigpotatoe** [comment]
> Does the saveFile/saveToFile methods overwrite or append the previous content of the file?
> Do I need to create the files and upload via arduinoIDE( example) before using it?

saveFile overrides what is in the file. If it were to append it would overflow the SPIFFS section eventaully without some sort of cleanup.

The intent of the library was to make an easy way to store variable data in flash with as little boiler plate as possible. So no, you do not have to upload anything, but you will need to make sure that a SPIFFS size greater than 0kB is selected in the IDE
