### ISSUE TITLE
append to a file?

### ISSUE THREAD

**Issue by jshep321** [thebigpotatoe/Effortless-SPIFFS#9]
is it possible to append to a file?  

I assume reading from the file, concatenating, and writing would work, but seems heavy duty, especially for larger files.

**Comment by thebigpotatoe** [comment]
>I assume reading from the file, concatenating, and writing would work, but seems heavy duty, especially for larger files.

I assume you are correct, haven't tested it, but that would make sense.

>is it possible to append to a file? 

It's not in the API as I have never used the append ability of the file systems for any of my projects. I shouldn't be hard to implement, but I just have to find the time to do it. Pull requests are also welcome :)  

Can I ask the application use for appending to a file in your case?

**Comment by happytm** [comment]
I agree with this request. I can use file containing sensor data with tabulator.js. http://tabulator.info/

**Comment by thebigpotatoe** [comment]
Due to popular demand see #10.

I have not tested the methods on hardware yet so feel free to do so. 

It should just work I'm hoping as it is just a copy and paste of the save to file methods. 

Let us know if it works for your application.

**Comment by jshep321** [comment]
Awesome.

Works as expected on my device (ESP32-WROOM).  Thanks!

**Comment by jshep321** [comment]
Any idea how long before this is merged into the (arduino/platformio) main branch?  I assume they pull directly from this github, but not 100% sure.

**Comment by thebigpotatoe** [comment]
So given it works, I have to pull it into the main branch and create a new version.

This will get pulled automatically by the platformio/arduino env after a couple of hours

**Comment by happytm** [comment]
@thebigpotatoe Is it possible to update example code with append method?

Thanks.

**Comment by jshep321** [comment]
Sure. A one word modification to your example is below:
```
//append to file using std::strings
  std::string newStdString;
  if (writeToFlash) {
    newStdString = "Hello World";
    fileSystem.appendToFile("/stdString.txt", newStdString);
  } else {
    fileSystem.openFromFile("/stdString.txt", newStdString);
  }
  Serial.print("std::string is: ");
  Serial.println(newStdString.c_str());
```

**Comment by happytm** [comment]
@jshep321 Thanks.
